jsapm: JSApm::GetInfo Class Reference
JSApm::GetInfo Class Reference
Class GetInfo. Parse AV_CONF_FILE or LOCAL_CONF_FILE and return information like the version, description, operator, line number and other.
#include <getinfo.h>
Public Member Functions
GetInfo (int idconf)
Constructor for GetInfo class. Initializes variables.
bool ParsePkg (std::string package)
bool ParseTag (std::string package, int tag_name)
bool ParseTag (std::string package, int tag_name, taginfo &taginfo_o)
bool PkgExist (std::string package)
bool TagExist (std::string, int tag_name)
bool GetPkgTag (std::string package, int tag_name, std::string &results_o, int &nline_o)
bool GetPkgTag (std::string package, int tag_name, std::string &results_o)
void get_DependsMap (std::string package, std::vector< Programa > &vector_depends)
Detailed Description
Class GetInfo. Parse AV_CONF_FILE or LOCAL_CONF_FILE and return information like the version, description, operator, line number and other.
Constructor & Destructor Documentation
GetInfo()
JSApm::GetInfo::GetInfo (int idconf)
Constructor for GetInfo class. Initializes variables.
Parameters
idconf (int) 1 or 2, 1 for get the pointer to the begin of the linked list, pertaining to AV_CONF_FILE, and 2 for LOCAL_CONF_FILE.
References JSApm::Read::get_begin().
Member Function Documentation
get_DependsMap()
void JSApm::GetInfo::get_DependsMap (std::string package, std::vector< Programa > & vector_depends)
Member that save information in a vector, about the dependencies.
Parameters
package Name of package.
vector_depends Dependencies of package.
References GetPkgTag(), _Programa::name, _Programa::nline, _Programa::op, and _Programa::ver.
Referenced by JSApm::Handle::handle_dependencies().
GetPkgTag() [1/2]
bool JSApm::GetInfo::GetPkgTag (std::string package, int tag_name, std::string & results_o, int & nline_o)
Member that return and save information for a tag in the respective variables.
Parameters
package Name of package.
tag_name Id for tag, defined in "tags_opts" variable.
results_o Variable in that save the content of the tag.
nline_o Variable in that save the line number of the tag.
Returns
True if the tag found, and return "False" if not found.
References taginfo::content, taginfo::nline, and ParseTag().
Referenced by get_DependsMap(), and JSApm::Handle::handle_dependencies().
GetPkgTag() [2/2]
bool JSApm::GetInfo::GetPkgTag (std::string package, int tag_name, std::string & results_o)
Member that return and save information for a tag in the respective variables.
Parameters
package Name of package.
tag_name Id for tag, defined in "tags_opts" variable.
results_o Variable in that save the content of the tag.
Returns
True if the tag found, and return "False" if not found.
References taginfo::content, and ParseTag().
ParsePkg()
bool JSApm::GetInfo::ParsePkg (std::string package)
Parse {AV|LOCAL}_CONF_FILE, searching package name.
Parameters
package Name of package.
Returns
"True" if the package found, and return "False" if not found.
Referenced by ParseTag(), and PkgExist().
ParseTag() [1/2]
bool JSApm::GetInfo::ParseTag (std::string package, int tag_name)
Parse {AV|LOCAL}_CONF_FILE, searching a tag.
Parameters
package Name of package.
tag_name Id for tag, defined in "tags_opts" variable.
Returns
"True" if the tag found, and return "False" if not found.
References ParsePkg().
Referenced by GetPkgTag(), and TagExist().
ParseTag() [2/2]
bool JSApm::GetInfo::ParseTag (std::string package, int tag_name, taginfo & taginfo_o)
Parse {AV|LOCAL}_CONF_FILE, searching a tag.
Parameters
package Name of package.
tag_name Id for tag, defined in "tags_opts" variable.
taginfo_o Struct in that save the results of the search, tag.
Returns
"True" if the tag found, and return "False" if not found.
References taginfo::content, taginfo::nline, and ParsePkg().
PkgExist()
bool JSApm::GetInfo::PkgExist (std::string package)
Verifies the existence of a package.
Parameters
package Name of package.
Returns
True if the package found, and return "False" if not found.
References ParsePkg().
Referenced by JSApm::Handle::handle_dependencies().
TagExist()
bool JSApm::GetInfo::TagExist (std::string package, int tag_name)
Verifies the existence of a tag.
Parameters
package Name of package.
tag_name Id for tag, defined in "tags_opts" variable.
Returns
True if the tag found, and return "False" if not found.
References ParseTag().
The documentation for this class was generated from the following files:
getinfo.h
getinfo.cpp