jsapm: JSApm::Read Class Reference
JSApm::Read Class Reference
#include <read.h>
Public Member Functions
Read (int idconf)
Constructor for Read class. Insert AV_CONF_FILE or LOCAL_CONF_FILE in memory, in order to increase speed of reading.
_node * get_begin ()
_node * new_node ()
Detailed Description
Class to insert in memory the file to parse.
Constructor & Destructor Documentation
Read()
JSApm::Read::Read (int idconf)
Constructor for Read class. Insert AV_CONF_FILE or LOCAL_CONF_FILE in memory, in order to increase speed of reading.
Parameters
idconf (int) 1 or 2, 1 for AV_CONF_FILE file and 2 for LOCAL_CONF_FILE.
References __node::line, new_node(), __node::next, and __node::nline.
Member Function Documentation
get_begin()
_node * JSApm::Read::get_begin ()
Member who return the begin(pointer) to the linked list.
Returns
Pointer at the beginning of the linked list.
Referenced by JSApm::GetInfo::GetInfo().
new_node()
_node * JSApm::Read::new_node ()
Member who create a node for the linked list.
Returns
Pointer to the create node.
References __node::line, and __node::next.
Referenced by Read().
The documentation for this class was generated from the following files:
read.h
read.cpp