jsapm: JSApm::Handle Class Reference
JSApm::Handle Class Reference
Class to entrust parse.
#include <handle.h>
Public Member Functions
Handle ()
candidates_struct handle_candidates (std::string package, std::string operate, std::string ver, int nline)
void handle_dependencies (std::string package, std::string operate, std::string ver, int nline)
void MsgError (std::map< std::string, meta >::iterator &iTmap)
void checkRepeatPkg (std::map< std::string, meta >::iterator &iTmap)
int isMoreEqualPkg (std::map< std::string, meta >::iterator &iTmap)
void insertPkgInRecSaver (std::map< std::string, meta >::iterator &iTmap, std::vector< meta_final > &vector_target, int is_more_equal)
candidates_struct parseOpAndFillCandStruct (std::vector< meta_final > &vector_origin)
Detailed Description
Class to entrust parse.
Class to entrust parse CONF_FILE, in it looks for dependencies, for the argument package.
Constructor & Destructor Documentation
Handle()
JSApm::Handle::Handle ()
Constructor for handle class.
Member Function Documentation
handle_candidates()
candidates_struct JSApm::Handle::handle_candidates (std::string package, std::string operate, std::string ver, int nline)
Takes an integer and squares it
Parameters
package Name of package
operate The operate, default is "0"
ver The version, default is "0"
nline The nline, default is 0
Returns
The struct who contents list of candidates for upgrade, install and revupgrade
References handle_dependencies().
handle_dependencies()
void JSApm::Handle::handle_dependencies (std::string package, std::string operate, std::string version, int nline)
Mmember that generate rec_saver map, who contains dependencies with aditional information.
Parameters
package Name of package
operate The operate, default is "0"
version The version, default is "0"
nline The nline, default is 0
References candidates_struct::candidates_new, candidates_struct::candidates_revupgrade, candidates_struct::candidates_upgrade, meta::data, JSApm::GetInfo::get_DependsMap(), JSApm::GetInfo::GetPkgTag(), meta_final::operate, meta_final::package, JSApm::GetInfo::PkgExist(), JSApm::Utils::transform_version(), and meta_final::version.
Referenced by handle_candidates().
The documentation for this class was generated from the following files:
handle.h
handle.cpp